---
- name: Create basix user
  user:
    name: basix
    groups: wheel
    shell: /bin/bash
    state: present
  remote_user: root

- name: Do not require password for sudo
  lineinfile:
    path: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
  remote_user: root
